23/4/2018
tmp.raw.sents 21382230 lines

pick 20w sents for training; 2w sents for dev; 2w sents for test


25/4/2018
Model/embedding:0

Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0
Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0

Model/embedding
Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/kernel
Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/bias
Model/RNN/multi_rnn_cell/cell_1/basic_lstm_cell/kernel
Model/RNN/multi_rnn_cell/cell_1/basic_lstm_cell/bias
Model/softmax_w
Model/softmax_b
Model/global_step

Traceback (most recent call last):
  File "ptb_word_lm.py", line 597, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 556, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 170, in __init__
    global_step=tf.train.get_or_create_global_step())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 451, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.
yyc@dlib-T630:/home1/yyc/Code/bilm-tf/lm$
Broadcast message from root@dlib-T630 on pts/45 (Wed 2018-04-25 22:57:55 +08):

The system is going down for poweroff at Wed 2018-04-25 22:58:55 +08!

